dirs:
  cache:
    root: '/home/osboxes/PycharmProjects/ccf/tmp/cache/'
    penncnp: penncnp
    ksads: ksads
  store:
    root: '/home/osboxes/PycharmProjects/ccf/tmp/store/'
    penncnp: penncnp
    ksads: ksads
box: '/home/osboxes/PycharmProjects/ccf/tmp/.boxApp/config.json'

root:
  cache: '/data/intradb/tmp/box2nda_cache/'
  store: '/home/shared/HCP/hcpinternal/ccf-nda-behavioral/store/'
config_files:
  box: /home/shared/HCP/hcpinternal/ccf-nda-behavioral/store/.boxApp/config.json
redcap:
  api_url: https://redcap.wustl.edu/redcap/srvrs/prod_v3_1_0_001/redcap/api/
  config: ../tmp/.boxApp/redcapconfig.csv
#  config: /home/shared/HCP/hcpinternal/ccf-nda-behavioral/store/.boxApp/redcapconfig.csv
ksads_snapshotfolderid: 48203202724
penn_snapshotfolderid:  48203214504
snapshotQCfolder: 76434619813
keyfileid: 265126641029
cachekeyfile: 506958838440
PennCNP:
  slim: 460781218444
  dict: 460884641280
  snapshot: 452784840845
Summaries:
  Intro:
    dict_id: 450219939565
    key_sheet: intro
    slim_id: 449745327689
  Screener:
    dict_id: 450226557492
    key_sheet: Screener
    slim_id: 449798152073
  Supplement:
    dict_id: 450238563945
    key_sheet: Supplement
    slim_id: 449779011618
Sites:
  WashU:
    Intro: 317203291349
    Screener: 317204091034
    Supplement: 317203382109
    ksads.net: 34
  Minn:
    Intro: 317226607001
    Screener: 317230106899
    Supplement: 317226471328
    ksads.net: 38
  UCLA:
    Intro: 317224169848
    Screener: 317224489061
    Supplement: 317224494224
    ksads.net: 36
  Harvard:
    Intro: 317223373321
    Screener: 317216055920
    Supplement: 317222199440
    ksads.net: 37
Assessments:
  Intro:
    cleanest_start:
      - 317203291349
      - 317226607001
      - 317224169848
      - 317223373321
    dict_id: 450219939565
    key_sheet: intro
    slim_id: 449745327689
  Screener:
    cleanest_start:
      - 317204091034
      - 317230106899
      - 317224489061
      - 317216055920
    dict_id: 450226557492
    key_sheet: Screener
    slim_id: 449798152073
  Supplement:
    cleanest_start:
      - 317203382109
      - 317226471328
      - 317224494224
      - 317222199440
    dict_id: 450238563945
    key_sheet: Supplement
    slim_id: 449779011618
