dirs:
  cache:
    root: '../tmp/cache/'
    penncnp: penncnp
    ksads: ksads
    qint: qint
  store:
    root: '../tmp/store/'
    penncnp: penncnp
    ksads: ksads
    qint: qint
box: '../creds/BoxApp.json'

root:
  cache: ../tmp/cache/
  store: ../tmp/store/
config_files:
  box: ../creds/BoxApp.json
redcap:
  api_url: https://redcap.wustl.edu/redcap/srvrs/prod_v3_1_0_001/redcap/api/
  config: ../creds/RedcapConfig.csv
KSADS:
  credentials: ../creds/KSADS.yml
ksads_snapshotfolderid: 48203202724
penn_snapshotfolderid:  48203214504
snapshotQCfolder: 76434619813
keyfileid: 265126641029
cachekeyfile: 506958838440
PennCNP:
  credentials: ../creds/PennCNP.yml
  slim: 460781218444
  dict: 460884641280
  snapshot: 452784840845
Summaries:
  Intro:
    dict_id: 450219939565
    key_sheet: intro
    slim_id: 449745327689
  Screener:
    dict_id: 450226557492
    key_sheet: Screener
    slim_id: 449798152073
  Supplement:
    dict_id: 450238563945
    key_sheet: Supplement
    slim_id: 449779011618
Sites:
  WashU:
    Intro: 317203291349
    Screener: 317204091034
    Supplement: 317203382109
    ksads.net: 34
  Minn:
    Intro: 317226607001
    Screener: 317230106899
    Supplement: 317226471328
    ksads.net: 38
  UCLA:
    Intro: 317224169848
    Screener: 317224489061
    Supplement: 317224494224
    ksads.net: 36
  Harvard:
    Intro: 317223373321
    Screener: 317216055920
    Supplement: 317222199440
    ksads.net: 37
Assessments:
  Intro:
    cleanest_start:
      - 317203291349
      - 317226607001
      - 317224169848
      - 317223373321
    dict_id: 450219939565
    key_sheet: intro
    slim_id: 449745327689
  Screener:
    cleanest_start:
      - 317204091034
      - 317230106899
      - 317224489061
      - 317216055920
    dict_id: 450226557492
    key_sheet: Screener
    slim_id: 449798152073
  Supplement:
    cleanest_start:
      - 317203382109
      - 317226471328
      - 317224494224
      - 317222199440
    dict_id: 450238563945
    key_sheet: Supplement
    slim_id: 449779011618
QIntColumns:
    RAVLT:
    - src_subject_id
    - pea_ravlt_sd_tc
    - delay_scaled
    - delay_completion
    - discontinue
    - reverse
    - pea_ravlt_sd_trial_i_tc
    - pea_ravlt_sd_trial_ii_tc
    - pea_ravlt_sd_trial_iii_tc
    - pea_ravlt_sd_trial_iv_tc
    - pea_ravlt_sd_trial_v_tc
    - pea_ravlt_sd_listb_tc
    - pea_ravlt_sd_trial_vi_tc
    - recall_correct_trial1
    - recall_correct_trial2
    - recall_correct_trial3
    - recall_correct_trial4
    - delay_recall_correct
    - delay_recall_intrusion
    - delay_total_intrusion
    - delay_total_repetitions
    RAVLT2:
    - src_subject_id
    - pea_ravlt_sd_tc
    - delay_scaled
    - delay_completion
    - discontinue
    - reverse
    - pea_ravlt_sd_trial_i_tc
    - pea_ravlt_sd_trial_ii_tc
    - pea_ravlt_sd_trial_iii_tc
    - pea_ravlt_sd_trial_iv_tc
    - pea_ravlt_sd_trial_v_tc
    - pea_ravlt_sd_listb_tc
    - pea_ravlt_sd_trial_vi_tc
    - recall_correct_trial1
    - recall_correct_trial2
    - recall_correct_trial3
    - recall_correct_trial4
    - delay_recall_correct
    - delay_recall_intrusion
    - delay_total_intrusion
    - delay_total_repetitions
    WAIS:
    - src_subject_id
    - scoring_matrixreasoning_raw
    - scoring_matrixreasoning_scaled
    - wais_dk
    - wais_nr
    - wais_p
    - matrix_completion
    - discontinue
    - reverse
    - matrixreasoning_a_resp
    - matrixreasoning_b_resp
    - matrixreasoning_1_score
    - matrixreasoning_2_score
    - matrixreasoning_3_score
    - matrixreasoning_4_score
    - matrixreasoning_5_score
    - matrixreasoning_6_score
    - matrixreasoning_7_score
    - matrixreasoning_8_score
    - matrixreasoning_9_score
    - matrixreasoning_10_score
    - matrixreasoning_11_score
    - matrixreasoning_12_score
    - matrixreasoning_13_score
    - matrixreasoning_14_score
    - matrixreasoning_15_score
    - matrixreasoning_16_score
    - matrixreasoning_17_score
    - matrixreasoning_18_score
    - matrixreasoning_19_score
    - matrixreasoning_20_score
    - matrixreasoning_21_score
    - matrixreasoning_22_score
    - matrixreasoning_23_score
    - matrixreasoning_24_score
    - matrixreasoning_25_score
    - matrixreasoning_26_score
    WISC:
    - src_subject_id
    - matrixreason_score
    - scaled_matrix
    - SubtestTypeDK
    - SubtestTypeNR
    - SubtestTypeSC
    - SubtestTypeSV
    - matrix_completion
    - discontinue
    - reverse
    - pea_wiscv_item_a_rs
    - pea_wiscv_item_b_rs
    - matrixreason_item1
    - matrixreason_item2
    - matrixreason_item3
    - matrixreason_item4
    - matrixreason_item5
    - matrixreason_item6
    - matrixreason_item7
    - matrixreason_item8
    - matrixreason_item9
    - matrixreason_item10
    - matrixreason_item11
    - matrixreason_item12
    - matrixreason_item13
    - matrixreason_item14
    - matrixreason_item15
    - matrixreason_item16
    - matrixreason_item17
    - matrixreason_item18
    - matrixreason_item19
    - matrixreason_item20
    - matrixreason_item21
    - matrixreason_item22
    - matrixreason_item23
    - matrixreason_item24
    - matrixreason_item25
    - matrixreason_item26
    - matrixreason_item27
    - matrixreason_item28
    - matrixreason_item29
    - matrixreason_item30
    - matrixreason_item31
    - matrixreason_item32
    WPPSI:
    - src_subject_id
    - wppsi_mxr_rawscre
    - wppsi_mxr_scldscre
    - wppsi_mxr_dk
    - wppsi_mxr_nr
    - wppsi_mxr_p
    - matrix_completion
    - discontinue
    - reverse
    - pea_wppsi_item_a_rs
    - pea_wppsi_item_b_rs
    - pea_wppsi_item_c_rs
    - matrixreason_item1
    - matrixreason_item2
    - matrixreason_item3
    - matrixreason_item4
    - matrixreason_item5
    - matrixreason_item6
    - matrixreason_item7
    - matrixreason_item8
    - matrixreason_item9
    - matrixreason_item10
    - matrixreason_item11
    - matrixreason_item12
    - matrixreason_item13
    - matrixreason_item14
    - matrixreason_item15
    - matrixreason_item16
    - matrixreason_item17
    - matrixreason_item18
    - matrixreason_item19
    - matrixreason_item20
    - matrixreason_item21
    - matrixreason_item22
    - matrixreason_item23
    - matrixreason_item24
    - matrixreason_item25
    - matrixreason_item26
