dirs:
  cache:
    root: '../tmp/cache/'
    penncnp: penncnp
    ksads: ksads
    qint: qint
  store:
    root: '../tmp/store/'
    penncnp: penncnp
    ksads: ksads
    qint: qint
box: '../creds/BoxApp.json'
root:
  cache: ../tmp/cache/
  store: ../tmp/store/
config_files:
  box: ../creds/BoxApp.json
Redcap:
  api_url: https://redcap.wustl.edu/redcap/srvrs/prod_v3_1_0_001/redcap/api/
  tables:
    hcpa:
      events: visit_1_arm_1
      fields:
        dobvar: dob
        field: subject_id
        interview_date: v1_date
        sexatbirth: gender
        sitenum: site
    hcpd18:
      events: visit_arm_1
      fields:
        dobvar: dob
        field: subject_id
        interview_date: intake_date
        sexatbirth: gender
        sitenum: site
    hcpdchild:
      events: visit_1_arm_1
      fields:
        dobvar: dob
        field: subject_id
        interview_date: intake_date
        sexatbirth: gender
        sitenum: site
    hcpdparent:
      events: visit_1_arm_1
      fields:
        dobvar: dob
        field: parent_id
        interview_date: intake_date
        sexatbirth: gender
        sitenum: site
secrets: ../secrets.yml
KSADS:
  download_dir: ./cache/raw_ksads/
  siteids:
    Harvard: 37
    Minn: 38
    UCLA: 36
    WashU: 34
  forms:
    - intro
    - screener
    - supplement
ksads_snapshotfolderid: 48203202724
penn_snapshotfolderid:  48203214504
snapshotQCfolder: 76434619813
keyfileid: 265126641029
cachekeyfile: 506958838440
PennCNP:
  credentials: ../creds/PennCNP.yml
  slim: 460781218444
  dict: 460884641280
  snapshot: 452784840845
Summaries:
  Intro:
    dict_id: 450219939565
    key_sheet: intro
    slim_id: 449745327689
  Screener:
    dict_id: 450226557492
    key_sheet: Screener
    slim_id: 449798152073
  Supplement:
    dict_id: 450238563945
    key_sheet: Supplement
    slim_id: 449779011618
Sites:
  WashU:
    Intro: 317203291349
    Screener: 317204091034
    Supplement: 317203382109
  Minn:
    Intro: 317226607001
    Screener: 317230106899
    Supplement: 317226471328
  UCLA:
    Intro: 317224169848
    Screener: 317224489061
    Supplement: 317224494224
  Harvard:
    Intro: 317223373321
    Screener: 317216055920
    Supplement: 317222199440
Assessments:
  Intro:
    cleanest_start:
      - 317203291349
      - 317226607001
      - 317224169848
      - 317223373321
    dict_id: 450219939565
    key_sheet: intro
    slim_id: 449745327689
  Screener:
    cleanest_start:
      - 317204091034
      - 317230106899
      - 317224489061
      - 317216055920
    dict_id: 450226557492
    key_sheet: Screener
    slim_id: 449798152073
  Supplement:
    cleanest_start:
      - 317203382109
      - 317226471328
      - 317224494224
      - 317222199440
    dict_id: 450238563945
    key_sheet: Supplement
    slim_id: 449779011618

Qint:
  BoxFolders:
    - 18446355408  # WUHCD
    - 18446433567  # WUHCA
    - 18446318727  # UMNHCD
    - 18446298983  # UMNHCA
    - 18446352116  # UCLAHCD
    - 18446404271  # UCLAHCA
    - 18446321439  # HARVHCD
    - 18446404071  # MGHHCA
    - 75755393630  # BDAS_HCD
    - 75755777913  # BDAS_HCA
  Columns:
    ravlt:
      - ravlt_pea_ravlt_sd_tc
      - ravlt_delay_scaled
      - ravlt_delay_completion
      - ravlt_discontinue
      - ravlt_reverse
      - ravlt_pea_ravlt_sd_trial_i_tc
      - ravlt_pea_ravlt_sd_trial_ii_tc
      - ravlt_pea_ravlt_sd_trial_iii_tc
      - ravlt_pea_ravlt_sd_trial_iv_tc
      - ravlt_pea_ravlt_sd_trial_v_tc
      - ravlt_pea_ravlt_sd_listb_tc
      - ravlt_pea_ravlt_sd_trial_vi_tc
      - ravlt_recall_correct_trial1
      - ravlt_recall_correct_trial2
      - ravlt_recall_correct_trial3
      - ravlt_recall_correct_trial4
      - ravlt_delay_recall_correct
      - ravlt_delay_recall_intrusion
      - ravlt_delay_total_intrusion
      - ravlt_delay_total_repetitions
    wais:
      - wais_scoring_matrixreasoning_raw
      - wais_scoring_matrixreasoning_scaled
      - wais_wais_dk
      - wais_wais_nr
      - wais_wais_p
      - wais_matrix_completion
      - wais_discontinue
      - wais_reverse
      - wais_matrixreasoning_a_resp
      - wais_matrixreasoning_b_resp
      - wais_matrixreasoning_1_score
      - wais_matrixreasoning_2_score
      - wais_matrixreasoning_3_score
      - wais_matrixreasoning_4_score
      - wais_matrixreasoning_5_score
      - wais_matrixreasoning_6_score
      - wais_matrixreasoning_7_score
      - wais_matrixreasoning_8_score
      - wais_matrixreasoning_9_score
      - wais_matrixreasoning_10_score
      - wais_matrixreasoning_11_score
      - wais_matrixreasoning_12_score
      - wais_matrixreasoning_13_score
      - wais_matrixreasoning_14_score
      - wais_matrixreasoning_15_score
      - wais_matrixreasoning_16_score
      - wais_matrixreasoning_17_score
      - wais_matrixreasoning_18_score
      - wais_matrixreasoning_19_score
      - wais_matrixreasoning_20_score
      - wais_matrixreasoning_21_score
      - wais_matrixreasoning_22_score
      - wais_matrixreasoning_23_score
      - wais_matrixreasoning_24_score
      - wais_matrixreasoning_25_score
      - wais_matrixreasoning_26_score
    wisc:
      - wisc_matrixreason_score
      - wisc_scaled_matrix
      - wisc_subtesttypedk
      - wisc_subtesttypenr
      - wisc_subtesttypesc
      - wisc_subtesttypesv
      - wisc_matrix_completion
      - wisc_discontinue
      - wisc_reverse
      - wisc_pea_wiscv_item_a_rs
      - wisc_pea_wiscv_item_b_rs
      - wisc_matrixreason_item1
      - wisc_matrixreason_item2
      - wisc_matrixreason_item3
      - wisc_matrixreason_item4
      - wisc_matrixreason_item5
      - wisc_matrixreason_item6
      - wisc_matrixreason_item7
      - wisc_matrixreason_item8
      - wisc_matrixreason_item9
      - wisc_matrixreason_item10
      - wisc_matrixreason_item11
      - wisc_matrixreason_item12
      - wisc_matrixreason_item13
      - wisc_matrixreason_item14
      - wisc_matrixreason_item15
      - wisc_matrixreason_item16
      - wisc_matrixreason_item17
      - wisc_matrixreason_item18
      - wisc_matrixreason_item19
      - wisc_matrixreason_item20
      - wisc_matrixreason_item21
      - wisc_matrixreason_item22
      - wisc_matrixreason_item23
      - wisc_matrixreason_item24
      - wisc_matrixreason_item25
      - wisc_matrixreason_item26
      - wisc_matrixreason_item27
      - wisc_matrixreason_item28
      - wisc_matrixreason_item29
      - wisc_matrixreason_item30
      - wisc_matrixreason_item31
      - wisc_matrixreason_item32
    wppsi:
      - wppsi_wppsi_mxr_rawscre
      - wppsi_wppsi_mxr_scldscre
      - wppsi_wppsi_mxr_dk
      - wppsi_wppsi_mxr_nr
      - wppsi_wppsi_mxr_p
      - wppsi_matrix_completion
      - wppsi_discontinue
      - wppsi_reverse
      - wppsi_pea_wppsi_item_a_rs
      - wppsi_pea_wppsi_item_b_rs
      - wppsi_pea_wppsi_item_c_rs
      - wppsi_matrixreason_item1
      - wppsi_matrixreason_item2
      - wppsi_matrixreason_item3
      - wppsi_matrixreason_item4
      - wppsi_matrixreason_item5
      - wppsi_matrixreason_item6
      - wppsi_matrixreason_item7
      - wppsi_matrixreason_item8
      - wppsi_matrixreason_item9
      - wppsi_matrixreason_item10
      - wppsi_matrixreason_item11
      - wppsi_matrixreason_item12
      - wppsi_matrixreason_item13
      - wppsi_matrixreason_item14
      - wppsi_matrixreason_item15
      - wppsi_matrixreason_item16
      - wppsi_matrixreason_item17
      - wppsi_matrixreason_item18
      - wppsi_matrixreason_item19
      - wppsi_matrixreason_item20
      - wppsi_matrixreason_item21
      - wppsi_matrixreason_item22
      - wppsi_matrixreason_item23
      - wppsi_matrixreason_item24
      - wppsi_matrixreason_item25
      - wppsi_matrixreason_item26
