root:
  cache: '/data/intradb/tmp/box2nda_cache/'
  store: '/home/shared/HCP/hcpinternal/ccf-nda-behavioral/store/'
config_files:
  box: /home/shared/HCP/hcpinternal/ccf-nda-behavioral/store/.boxApp/config.json
redcap:
  api_url: https://redcap.wustl.edu/redcap/srvrs/prod_v3_1_0_001/redcap/api/
  config: /home/shared/HCP/hcpinternal/ccf-nda-behavioral/store/.boxApp/redcapconfig.csv
ksads_snapshotfolderid: 48203202724
snapshotQCfolder: 76434619813
keyfileid: 265126641029
Assessments:
  Intro:
    cleanest_start:
      - 317203291349
      - 317226607001
      - 317224169848
      - 317223373321
    dict_id: 450219939565
    key_sheet: intro
    slim_id: 449745327689
  Screener:
    cleanest_start:
      - 317204091034
      - 317230106899
      - 317224489061
      - 317216055920
    dict_id: 450226557492
    key_sheet: Screener
    slim_id: 449798152073
  Supplement:
    cleanest_start:
      - 317203382109
      - 317226471328
      - 317224494224
      - 317222199440
    dict_id: 450238563945
    key_sheet: Supplement
    slim_id: 449779011618
